name: Main Docker Image CD

on:
  push:
    branches: [ "main" ]

jobs:

  buildpush:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image for development
      run: docker build --target development . --tag ${{ secrets.DOCKERHUB_USERNAME }}/flask-mio:dev

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-mio:dev